image: lorisleiva/laravel-docker:latest
#include:
#  - template: Security/SAST.gitlab-ci.yml
#  - template: Security/Dependency-Scanning.gitlab-ci.yml

variables:
  XDEBUG_MODE: coverage
composer:
  stage: build
  cache:
    key: "${CI_COMMIT_REF_SLUG}-composer"
    paths:
      - vendor/
  script:
    - export COMPOSER_NO_DEV=0
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.gitlab .env
    - php artisan key:generate
  artifacts:
    expire_in: 1 month
    when: always
    paths:
      - vendor/
      - ".env"
npm:
  # Same stage as `composer` so that they run in parallel.
  stage: build

  # Cache the `node_modules` folder
  # using the `npm` suffix on the key.
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

  # Install and compile.
  script:
    - npm install --save-dev vite laravel-vite-plugin
    - npm run build

  # Provide the other jobs of the pipeline with
  # the node dependencies and the compiled assets.
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/
pint:
  stage: test
  dependencies:
    - composer
  script:
    - php ./vendor/bin/pint
test:
  variables:
    XDEBUG_MODE: coverage
  stage: test
  dependencies:
    - composer
    - npm
  script:
    - npm install --save-dev vite laravel-vite-plugin
    - npm run build
    - export XDEBUG_MODE=coverage
    - touch coverage.cobertura.xml
    - touch report.xml
    - chmod 777 coverage.cobertura.xml
    - chmod 777 report.xml
    - php -d memory_limit=4G ./vendor/bin/pest --coverage --coverage-cobertura=coverage.cobertura.xml --colors=never --log-junit report.xml
  artifacts:
    when: always
    reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.cobertura.xml
        junit: report.xml
  coverage: /\bTotal\b.*?(\d+\.\d+)/
deploy_prod:
  when: manual
  stage: deploy
  script:
    - curl https://forge.laravel.com/servers/546270/sites/2208781/deploy/http?token=D1p66liZmO0Ru80KxY8b8dSHpKskGnHeHhLrsYMu
    - exit 0
  only:
    - main
  environment:
    name: production
    url: https://www.theperfectcodedev.com
