image: lorisleiva/laravel-docker:latest
#include:
#  - template: Security/SAST.gitlab-ci.yml
#  - template: Security/Dependency-Scanning.gitlab-ci.yml

variables:
  XDEBUG_MODE: coverage
composer:
  stage: build
  cache:
    key: "${CI_COMMIT_REF_SLUG}-composer"
    paths:
      - vendor/
  script:
    - export COMPOSER_NO_DEV=0
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.gitlab .env
    - php artisan key:generate
    - npm install --save-dev vite laravel-vite-plugin
    - npm run build
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - ".env"
pint:
  stage: test
  dependencies:
    - composer
  script:
    - php ./vendor/bin/pint
test:
  variables:
    XDEBUG_MODE: coverage
  stage: test
  dependencies:
    - composer
  script:
    #- php ./vendor/bin/pest --coverage-cobertura=coverage.xml --coverage-text --colors=never
    - npm install --save-dev vite laravel-vite-plugin
    - npm run build
    - php -d memory_limit=4G ./vendor/bin/pest --coverage-text --coverage-cobertura=coverage.cobertura.xml --colors=never --stderr --log-junit report.xml
  artifacts:
    when: always
    reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.cobertura.xml
        junit: report.xml
  coverage: '/^\s*Lines:\s*(\d+\.\d+)\%/'