name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Laravel Forge Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://www.theperfectcodedev.com/"
    steps:
      - name: Deploy
        uses: PropFuel/laravel-forge-deploy-action@v1.0.1
        with:
          forge-api-token: ${{ secrets.FORGE_API_TOKEN }}
          forge-server-id: ${{ secrets.FORGE_SERVER_ID }}
          forge-site-id: ${{ secrets.FORGE_SITE_ID }}