name: Deploy on push to main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Laravel Forge Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: PropFuel/laravel-forge-deploy-action@v1.0.1
        with:
          forge-api-token: ${{ secrets.FORGE_API_TOKEN }}
          forge-server-id: ${{ secrets.FORGE_SERVER_ID }}
          forge-site-id: ${{ secrets.FORGE_SITE_ID }}
